apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-rclone
  labels:
    name: data-rclone
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  storageClassName: rclone
  csi:
    driver: csi-rclone
    volumeHandle: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rclone
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rclone
  selector:
    matchLabels:
      name: data-rclone
---
apiVersion: v1
kind: Pod
metadata:
  name: package-file
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-rclone
  - name: results
    emptyDir: {}
  initContainers:
  - image: ghcr.io/almahmoud/gha-build-anvil-jupyter-amd64:linux-amd64
    imagePullPolicy: Always
    name: copy-packages
    volumeMounts:
      - mountPath: /mnt/pkgs
        name: data
      - mountPath: /mnt/results
        name: results
    command: ['/bin/sh']
    args:
    - "-c"
    - set -x; Rscript -e 'tools::write_PACKAGES("/mnt/pkgs", addFiles = TRUE, verbose = TRUE)' && cp /mnt/pkgs/PACKAGES* /mnt/results/
  containers:
  - image: ghcr.io/almahmoud/gha-build-anvil-jupyter-amd64:linux-amd64
    imagePullPolicy: IfNotPresent
    name: sleep
    volumeMounts:
      - mountPath: /mnt/results
        name: results
    command: ['/bin/sh']
    args:
    - "-c"
    - sleep 3000
---
