name: Create PACKAGES file for the R repository
on:
  workflow_dispatch: {}
  push:
    paths:
      - lists/write_PACKAGES
jobs:
  writepkgs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Start a local k8s cluster
        uses: jupyterhub/action-k3s-helm@v3
        with:
          k3s-channel: latest
          metrics-enabled: false
          traefik-enabled: false

      - name: Verify function of k8s, kubectl, and helm
        run: |
          kubectl version
          helm version
          
          git clone --depth=1 https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner.git
          
          cat << "EOF" > local.yaml
          classes:
          - name: local-storage
            hostDir: /mnt/disks
            volumeMode: Block
            storageClass: true
          EOF
          
          kubectl create ns rclone
          helm install -n rclone static ./sig-storage-local-static-provisioner/helm/provisioner -f local.yaml
  
          helm repo add wunderio https://storage.googleapis.com/charts.wdr.io
          echo "$RCLONE_VALS" > rclone-vals.yaml
          sed -i "s#HOLDERPATH#gha-build/$(cat containername)/$(cat arch)/$(cat runstarttime)/binaries#g" rclone-vals.yaml
          helm upgrade --install --create-namespace -n rclone rclone wunderio/csi-rclone -f rclone-vals.yaml --wait
          kubectl -n rclone apply -f .github/scripts/k8s/k8s-resources.yaml
          while [[ $(kubectl get pods -n rclone package-file --no-headers -o custom-columns=":status.phase") != "Ready" ]]; do
            echo $(kubectl get pods -n rclone package-file --no-headers -o custom-columns=":status.phase")
            kubectl get events -n rclone
            kubectl get all -n rclone
            echo "\n\n\n\n\n\n"
            kubectl logs -n rclone pod/csi-controller-rclone-0 -c rclone
            echo "\n\n\n\n\n\n"
            kubectl get pods -n rclone package-file -o yaml
            sleep 1
          done
          mkdir -p /tmp
          kubectl cp -c sleep -n rclone package-file:/mnt/results/PACKAGES.gz /tmp/PACKAGES.gz
          kubectl cp -c sleep -n rclone package-file:/mnt/results/PACKAGES.rds /tmp/PACKAGES.rds
          kubectl cp -c sleep -n rclone package-file:/mnt/results/PACKAGES /tmp/PACKAGES
        env:
          RCLONE_VALS: ${{secrets.RCLONE_VALS}}

      - name: Install rclone & add rclone conf file
        uses: nick-fields/retry@v2
        env:
            RCLONE_CONF: ${{secrets.RCLONE_CONF}}
        with:
          timeout_minutes: 20
          max_attempts: 10
          shell: bash
          command: |
            set -xe
            sudo -v ; curl https://rclone.org/install.sh | sudo bash || true
            echo "$RCLONE_CONF" > ~/.rclone.conf
            if ! command -v rclone &> /dev/null
            then
                echo "rclone could not be found"
                exit 1;
            fi

      - run: |
          rclone copyto /tmp/PACKAGES js2:/gha-build/$(cat containername)/$(cat arch)/$(cat runstarttime)/PACKAGES -vvvvv
          rclone copyto /tmp/PACKAGES.gz js2:/gha-build/$(cat containername)/$(cat arch)/$(cat runstarttime)/PACKAGES.gz -vvvvv
          rclone copyto /tmp/PACKAGES.rds js2:/gha-build/$(cat containername)/$(cat arch)/$(cat runstarttime)/PACKAGES.rds -vvvvv
